### ISSUE TITLE
Windows test suite

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#115]
Ensure test suite is run with Windows testing actions.

Following from #106
> Also, the Windows testing actions logs do not suggest that the test suite was actually run. In particular, there is no standard output logging from your testing script.

**Comment by mosesyhc** [comment]
@jared321 : I attempted running the test suite on Windows in two ways:
- run `tox -e coverage` within Windows Powershell to invoke the test suite.  The tests are correctly run. 
- run `.\tests\run-tests.sh` directly in Powershell.  The tests are also correctly run.
  - Details: I had to reinstall cython (somehow `pyximport` is missing)

I am unsure how this would be different if run by the Windows actions. Any idea on how I can further test?

**Comment by jared321** [comment]
Do you see the correct pytest output when you run locally?  If so, then I would suggest
* breaking a test,
* run locally with tox to confirm that the test reports an error,
* alter the GH action so that it will only run the windows tests,
* commit the code that breaks the tests.

If the Windows CI tests are running but simply not logging the pytest standard output, you should see the Windows test fail.  If the test doesn't fail, then run just the Ubuntu tests in the action.  If that fails, then we have a problem.

**Comment by mosesyhc** [comment]
Solved via using tox in github action [a3a9592](https://github.com/bandframework/surmise/pull/118/commits/a3a9592f3f81bf22df84cbbeeefd20592d81e87d)
