### ISSUE TITLE
readthedocs build failure not carried forward to github action

### ISSUE THREAD

**Issue by mosesyhc** [bandframework/surmise#139]
Build action completed while readthedocs reported failure, see

https://readthedocs.org/projects/surmise/builds/25524079/

**Comment by mosesyhc** [comment]
Some investigation:

In RTD, between build [25464477](https://readthedocs.org/projects/surmise/builds/25464477/) and build [25462853](https://readthedocs.org/projects/surmise/builds/25462853/) is when the build has failed. 

The commits between the two builds seem to indicate no problem.

But Sphinx v7.4.7 and v8.0.2 are called respectively in the two builds. With Sphinx v8.0.2, RTD build seems to fail, but does not notify GH action.

**Comment by mosesyhc** [comment]
One solution is to specify Sphinx version for now - but we should maybe look deeper..

**Comment by jared321** [comment]
Local and GH action builds use tox, which has been setup so that all sphinx dependencies are always installed.  Therefore, these pass.

The RTD config was originally specified to install the "docs" optional dependencies as specified in `pyproject.yaml`.  However, at commit b56e0c3fedd4834a82207e7f5c13b29a16cf1efb, we removed those to keep things simpler and because users don't need to build the docs.  Hence the failure.

At commit e6f7e349c86b7721c9001558dd7bcc87bb3111d2, we included these dependencies in a requirements file bundled with the doc files.  We presently prefer this method since it still keeps things simpler and the deps are specified in a more direct way.  Also, the package might need to eventually move to using only a `setup.py`, which is compatible with the current implementation.

Closed.
