### ISSUE TITLE
Conflict with setuptools

### ISSUE THREAD

**Issue by jmlarson1** [bandframework/surmise#97]
Hello Surmise dev team. GitHub Actions are complaining when building surmise, reporting an issue with setuptools. 

Example here:
https://github.com/Libensemble/libensemble/actions/runs/7051634257/job/19194985576#step:12:97

This is a recent issue because surmise built without an issue two weeks ago:
https://github.com/Libensemble/libensemble/actions/runs/6920849915/job/18825771922

We just wanted to let you know.

**Comment by mosesyhc** [comment]
@jmlarson1: Apologies for not seeing this issue earlier.  I implemented a patch for the optional dependencies flag in the develop branch.  I tried re-running the linked failed job but did not trigger surmise installation.  

Which branch of libensemble should I test on?

**Comment by mosesyhc** [comment]
@jmlarson1: We have implemented the patch for both develop and main branch for surmise. We believe the issue for building surmise should be solved.  After a successful CI action, we can move to close this issue.

Also, I would like to suggest we update the reference of surmise to it's main branch instead of the develop branch, because the branches have synced since the last update.

**Comment by jmlarson1** [comment]
Great. We've re-triggered our GitHub Actions and surmise now builds without issue:
https://github.com/Libensemble/libensemble/actions/runs/7108066874

libEnsemble tests are using the default branch (instead of develop). Thank you very much @mosesyhc!
